import os
from typing import List, Dict, Any
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser

load_dotenv()

class LLMResponse(BaseModel):
    answer: str = Field(description="Answer grounded in the provided document chunks")
    citations: List[str] = Field(description="List of citations in format 'filename: page N'")

SYSTEM_PROMPT = """You are a clinical guidelines assistant. You answer questions strictly based on the provided document excerpts.

Rules:
- Only use information present in the provided chunks.
- If the answer is not found in the chunks, say so explicitly — do not invent information.
- Always cite the source document and page number for every claim.
- Do not provide personal medical advice or diagnosis."""

#Scope gate runs before touching the LLM — cheap keyword check that short-circuits the whole chain for off-topic queries.
SCOPE_KEYWORDS = [
    "diagnosis", "treatment", "dosage", "screening", "guideline",
    "symptom", "medication", "protocol", "prevention", "management",
    "therapy", "vaccine", "immunization", "dose", "drug", "disease",
    "condition", "patient", "clinical", "health", "medical"
]

def is_in_scope(query: str) -> tuple[bool, str | None]:
    if any(kw in query.lower() for kw in SCOPE_KEYWORDS):
        return True, None
    return False, "Query does not appear to relate to clinical guidelines covered by loaded documents."

#Formats reranked chunks into a numbered, labelled block. Source and page are inline so the model can cite them directly from what it reads.
def build_context(chunks: List[Dict[str, Any]]) -> str:
    parts = []
    for i, chunk in enumerate(chunks):
        source = os.path.basename(chunk["source"])
        parts.append(f"[Chunk {i+1} | Source: {source} | Page: {chunk['page']}]\n{chunk['text']}")
    return "\n\n".join(parts)

#prompt | llm | parser is a LangChain LCEL chain (LangChain Expression Language). Data flows left to right — 
# prompt formats the messages, LLM generates, parser extracts structured JSON. format_instructions is 
# auto-generated by JsonOutputParser from the Pydantic schema and injected into the prompt so the model knows 
# the exact output shape expected.

parser = JsonOutputParser(pydantic_object=LLMResponse)

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    ("user", """Answer the following question using only the document excerpts below.

{format_instructions}

Question: {query}

Document excerpts:
{context}
""")
])

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

chain = prompt | llm | parser

def generate(query: str, reranked_chunks: List[Dict[str, Any]], retrieved_chunks: List[Dict[str, Any]]) -> Dict[str, Any]:
    in_scope, refusal_reason = is_in_scope(query)

    if not in_scope:
        return {
            "query": query,
            "retrieved_chunks": retrieved_chunks,
            "reranked_chunks": reranked_chunks,
            "answer": None,
            "citations": [],
            "is_in_scope": False,
            "refusal_reason": refusal_reason,
        }

    context = build_context(reranked_chunks)

    raw = chain.invoke({
        "query": query,
        "context": context,
        "format_instructions": parser.get_format_instructions(),
    })

    return {
        "query": query,
        "retrieved_chunks": [
            {"text": c["text"], "source": c["source"], "score": c["distance"]}
            for c in retrieved_chunks
        ],
        "reranked_chunks": [
            {"text": c["text"], "source": c["source"], "rerank_score": c["rerank_score"]}
            for c in reranked_chunks
        ],
        "answer": raw.get("answer"),
        "citations": raw.get("citations", []),
        "is_in_scope": True,
        "refusal_reason": None,
    }
